<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Renderer for the Diary module (modern namespaced version).
 *
 * @package   mod_diary
 * @copyright 2019 onwards AL Rachels drachels@drachels.com
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace mod_diary\output;

use plugin_renderer_base;
use stdClass;
use moodle_url;
use html_writer;
use context_module;

/**
 * Diary reports renderable.
 *
 * @since      Moodle 4.0
 * @package    mod_diary
 * @copyright  2019 AL Rachels (drachels@drachels.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class renderer extends plugin_renderer_base {
    /**
     * Return introduction box and content for the page generated by view.php file.
     *
     * @param stdClass $diary Diary activity this description is for.
     * @param stdClass $cm Course module this description is for.
     * @return string HTML
     */
    public function introduction($diary, $cm) {
        $output = '';

        if (trim($diary->intro)) {
            $output .= $this->box_start('generalbox boxaligncenter', 'intro');
            $output .= format_module_intro('diary', $diary, $cm->id);
            $output .= $this->box_end();
        }
        return $output;
    }

    /**
     * Print the toolbar above the entries on the page generated by view.php.
     *
     * @param int $firstkey Id of the entry for the current sort order (or 0).
     * @param stdClass|array $cm Course module object or array with at least 'id'
     * @return string HTML for toolbar buttons
     */
    public function toolbar($firstkey, $cm) {
        // Normalize $cm to always have 'id' (old code sometimes passed array).
        $cmid = is_object($cm) ? $cm->id : ($cm['id'] ?? 0);

        $options = ['id' => $cmid];
        $output = ' ';

        // Export to .csv.
        $options['action'] = 'download';
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('i/export', get_string('csvexport', 'diary')),
            ['class' => 'toolbutton']
        );

        // Reload.
        $options['action'] = 'reload';
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('t/reload', get_string('reload', 'diary')),
            ['class' => 'toolbutton']
        );

        // Edit top-of-list entry.
        $options['action'] = 'editentry';
        $options['firstkey'] = $firstkey;
        $options['promptid'] = $cm['promptid'] ?? 0; // Safe fallback.
        $url = new moodle_url('/mod/diary/edit.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('i/edit', get_string('edittopoflist', 'diary')),
            ['class' => 'toolbutton']
        );

        // Sort to first entry.
        $options['action'] = 'sortfirstentry';
        $options['firstkey'] = $firstkey;
        unset($options['promptid']); // Not needed here.
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('t/left', get_string('sortfirstentry', 'diary')),
            ['class' => 'toolbutton']
        );

        // Lowest grade entry.
        $options['action'] = 'lowestgradeentry';
        $options['firstkey'] = $firstkey;
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('t/down', get_string('lowestgradeentry', 'diary')),
            ['class' => 'toolbutton']
        );

        // Highest grade entry.
        $options['action'] = 'highestgradeentry';
        $options['firstkey'] = $firstkey;
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('t/up', get_string('highestgradeentry', 'diary')),
            ['class' => 'toolbutton']
        );

        // Latest modified entry.
        $options['action'] = 'latestmodifiedentry';
        $options['firstkey'] = $firstkey;
        $url = new moodle_url('/mod/diary/view.php', $options);
        $output .= html_writer::link(
            $url,
            $this->pix_icon('t/right', get_string('latestmodifiedentry', 'diary')),
            ['class' => 'toolbutton']
        );

        return $output;
    }

    /**
     * Returns HTML for a diary inaccessible message.
     *
     * @param string $message
     * @return string HTML
     */
    public function diary_inaccessible($message) {
        global $CFG;

        $output = $this->box_start('generalbox boxaligncenter');
        $output .= $this->box_start('center');
        $output .= get_string('notavailable', 'diary');
        $output .= $message;
        $output .= $this->box(
            html_writer::link(
                new moodle_url('/course/view.php', ['id' => $this->page->course->id]),
                get_string('returnto', 'diary', format_string($this->page->course->fullname))
            ),
            'diarybutton standardbutton'
        );
        $output .= $this->box_end();
        $output .= $this->box_end();

        return $output;
    }

    // The existing mustache/reportone methods (unchanged).
    /**
     * Renders the reportone page.
     *
     * @param stdClass $data Data for the template
     * @return string HTML
     */
    public function render_reportone(stdClass $data) {
        return $this->render_from_template('mod_diary/reportone', $data);
    }

    /**
     * Prepares context data for reportone.mustache.
     *
     * @param stdClass $cm Course module
     * @param stdClass $course Course
     * @param stdClass $diary Diary instance
     * @param stdClass $user User record
     * @param stdClass $entry Diary entry (or null)
     * @param array $teachers Teachers list (for feedback)
     * @param array $grades Grades menu
     * @return stdClass Template context
     */
    public function prepare_reportone_data($cm, $course, $diary, $user, $entry, $teachers, $grades) {
        global $USER;

        $context = context_module::instance($cm->id);

        $data = new stdClass();
        $data->cmid        = $cm->id;
        $data->diaryname   = format_string($diary->name, true, ['context' => $context]);
        $data->entrybgc    = $diary->entrybgc ?? '#ffffff'; // Default white if unset.
        $data->sesskey     = sesskey();
        $data->formaction  = (new moodle_url('/mod/diary/reportone.php', [
            'id' => $cm->id, 'user' => $user->id, 'entryid' => $entry ? $entry->id : 0, 'action' => 'currententry',
        ]))->out(false);

        // Back link to index.php (all diaries? or adjust if it's to report.php).
        $data->backlink = (object)[
            'url' => (new moodle_url('/mod/diary/index.php', ['id' => $course->id]))->out(),
        ];

        $data->heading = $data->diaryname; // Or customize.

        // Entry content.
        if ($entry) {
            // Capture the output of diary_print_user_entry as raw HTML string.
            ob_start();
            \mod_diary\local\results::diary_print_user_entry(
                $context,
                $course,
                $diary,
                $user,
                $entry,
                $teachers,
                $grades
            );
            $data->entryhtml = ob_get_clean();
            $data->hasentry = true;
        } else {
            $data->entryhtml = '';
            $data->hasentry  = false;
        }

        // Save/return buttons (shown if entry exists and capability allows).
        $data->savebuttons = has_capability('mod/diary:manageentries', $context);
        if ($data->savebuttons) {
            $data->returnlink = (object)[
                'url' => (new moodle_url('/mod/diary/report.php', ['id' => $cm->id, 'action' => 'currententry']))->out(),
            ];
        }

        return $data;
    }

    /**
     * Renders the index.php page (list of Diary instances in a course).
     *
     * @param stdClass $course The course record.
     * @param array $instances Array of diary instances (with extra computed fields).
     * @param bool $showlastmodified Whether to show last modified column.
     * @param bool $showentries Whether to show entry count column (if plugin supports).
     * @return string HTML
     */
    public function render_index_page(
        stdClass $course,
        array $instances,
        bool $showlastmodified = true,
        bool $showentries = false
    ) {
        $data = $this->prepare_index_data($course, $instances, $showlastmodified, $showentries);
        return $this->render_from_template('mod_diary/index_page', $data);
    }

    /**
     * Prepares context data for index_page.mustache
     */
    protected function prepare_index_data(
        stdClass $course,
        array $instances,
        bool $showlastmodified = true,
        bool $showentries = false
    ) {
        $data = new stdClass();
        $data->heading = get_string('modulenameplural', 'diary') . ' in ' . format_string($course->fullname);
        $data->hasinstances = !empty($instances);
        $data->totalinstances = count($instances);
        $data->showsections   = course_format_uses_sections($course->format);  // Add this for conditional column.
        $data->showentries    = $showentries;
        $data->courseformat   = $course->format;  // For string in template if needed.

        $data->instances = $instances;  // Already prepared in index.php.

        return $data;
    }
}
